### ISSUE TITLE
Preview slidetabs not working 

### ISSUE THREAD

**Issue by zokni1996** [jahirfiquitiva/PaperBoard#10]
When I open the application, and move to the Icon section, it load successful. After that if I press back, or simply just move an other section, and then move back, the tabs not load, I can't swipe (I can, but like a list)...

**Comment by jahirfiquitiva** [comment]
Yes.
Sadly is a known issue, but it doesn't happens always, it works almost always.
There's no fix for now. (At least from myself).

**Comment by zokni1996** [comment]
Can I reccomend to use https://github.com/astuetz/PagerSlidingTabStrip?

**Comment by jahirfiquitiva** [comment]
It doesn't have ripples by default when pressing the tabs. I talked with dev and he will include them in a future update.
I will use it then.

**Comment by zokni1996** [comment]
Ok :+1: :)
