### ISSUE TITLE
Finalize wallpaper viewer's shared element transitions

### ISSUE THREAD

**Issue by afollestad** [jahirfiquitiva/PaperBoard#13]
Wallpapers should be displayed fullscreen so the user can preview what it'd look like on their home screen. Shared element transitions should also be used to animate the image from the grid to the full detail view.

**Comment by afollestad** [comment]
@jahirfiquitiva the basic viewer is now pushed if you want to try it, the shared element transition isn't perfect yet though

**Comment by jahirfiquitiva** [comment]
@afollestad Thank you so much. I will test it soon. I wanted to ask you something else.
Is possible for you to add the possibility of searching icons in the Icons section?
Thanks in advance.

**Comment by afollestad** [comment]
Icon search is done

**Comment by jahirfiquitiva** [comment]
Thank you SO much! Again.

**Comment by afollestad** [comment]
Wait there appears to be a glitch, hold on

**Comment by afollestad** [comment]
This isn't quite done

**Comment by jahirfiquitiva** [comment]
@afollestad

**Comment by jahirfiquitiva** [comment]
@afollestad  but this source won't have this feature. Only private repo will.
