### ISSUE TITLE
Switch to using RecyclerViews everywhere

### ISSUE THREAD

**Issue by afollestad** [jahirfiquitiva/PaperBoard#14]

**Comment by jahirfiquitiva** [comment]
And sort Launchers list by Installed first. <b>If possible.</b> Thanks in advance.

**Comment by afollestad** [comment]
Done, have to test it now.

Also, the installed state of a launcher is cached since checking if a package is installed is slightly intensive. The grid width for wallpapers and icons are loaded from a value in integers.xml, which is different for different screen sizes (values, values-sw600dp, and the landscape versions).

**Comment by jahirfiquitiva** [comment]
Thank you SO much.
