### ISSUE TITLE
Fix issues with clicking icon search results

### ISSUE THREAD

**Issue by afollestad** [jahirfiquitiva/PaperBoard#18]
This doesn't always occur but it seems to happen most of the time (search results are unclickable).

**Comment by jahirfiquitiva** [comment]
I just noticed it.
I was also thinking if it could be possible to show the results that start with what I typed in the search bar, instead of the one that contains what I typed. I'm not sure if you understand me.

**Comment by afollestad** [comment]
The commit I just pushed uses `startsWith()` instead of `contains()` :)

I'll have to look into this bug tomorrow, unless you figure it out first

**Comment by jahirfiquitiva** [comment]
I think I will wait. I will also give it a look by the way. But I will wait anyways.
Thanks for everything you did today. Can't wait for the other stuff. :)

**Comment by afollestad** [comment]
Cool, you're welcome :)
