### ISSUE TITLE
Problem Elevation Toolbar

### ISSUE THREAD

**Issue by helmifluida** [jahirfiquitiva/PaperBoard#21]
In toolbar background i using @drawable, but this problem because shadow elevation not show, how fix it ??????? :(

**Comment by jahirfiquitiva** [comment]
This isn't an issue with PaperBoard. When you go working on your own modifications is your work to fix them too.

The issues here are supposed to be the original source issues, not your modifications issues.

Anyways, to answer your question...

I don't understand why do you use a drawable. In Material Design, toolbars are supposed to be just one color, as already done in the source.

Btw, just want to mention some possibilities that may be causing your issue:
- Elevation only works on API 21+ or Android 5.x +

If you are using an Android 5.x + device, and still don't get the shadow, that's an issue with your modification and as in the tutorial says: "your own modifications, are your own responsibility and risk".

If you are using a pre-lollipop device, then, you already know what's the issue.

**Comment by helmifluida** [comment]
Thanks fast respon :)
