### ISSUE TITLE
I can't change app_one_package and app_two_package.

### ISSUE THREAD

**Issue by hansstark** [jahirfiquitiva/PaperBoard#22]
Hello..

Thank you for template and tutorial but i have some problem. I can't change the cards in the main screen. I can change all play_card and all app_three but i can't change app_one_package and app_two_package on strings.xml. I can change app_one_title, app_one_content, app_two_title, app_two_content but i can't change app_one_package and app_two_package. When i change app_one_package or app_two_package, this cards don't see in the app. How can i fix it?

Thank you so much again. You did a great job.
Sorry for my English, i hope you understand me :)

![issue](https://cloud.githubusercontent.com/assets/13300479/8638240/97fea8bc-28bd-11e5-9d1b-9fbb0b8bbba9.png)
![screenshot_2015-07-12-17-38-17](https://cloud.githubusercontent.com/assets/13300479/8638249/edb6cb90-28bd-11e5-9439-b9a6da393d70.jpg)

**Comment by jahirfiquitiva** [comment]
The app will check if you have the apps with those package names already installed in your device, so you won't be bothering users to install apps that they already have.

Try setting the packages you want, and if you have those apps installed in your device, uninstall them and the cards should appear.

**Comment by hansstark** [comment]
Thank you again, you are so fast :)
